### ISSUE TITLE
Export different User interface for backend and different for frontend/sdks

### ISSUE THREAD

**Issue by kymppi** [rittaschool/shared#4]

**Comment by kymppi** [comment]
The interface for backend should be exported at @rittaschool/backend/User and for frontend at @rittaschool/User. They would differ by removing password and other sensitive fields from the backend user interface.

**Comment by kymppi** [comment]
i meant removing sensitive fields from the frontend interface

**Comment by kymppi** [comment]
@raikasdev why didnt you close this issue as i see you completed it?

**Comment by raikasdev** [comment]
I forgor 💀

**Comment by kymppi** [comment]
![image](https://user-images.githubusercontent.com/48528700/145586519-8c7b80b8-d4b5-4e09-a207-ce93586f6d1e.png)
